export { Navbar } from './navbar'
export { Footer } from './footer'
export { Hero } from './hero'
export { Features } from './features'
export { Pricing } from './pricing'
export { FAQ } from './faq'
